### ISSUE TITLE
Updating to 2024 beta breaks

### ISSUE THREAD

**Issue by spacey-sooty** [CurtinFRC/2024-Crescendo#20]
**Describe the bug**
When I bump the version to 2024.1.1-beta-3 I get the error
```
FAILURE: Build failed with an exception.

* What went wrong:
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/gradle/api/flow/FlowAction
> java.lang.NoClassDefFoundError: org/gradle/api/flow/FlowAction

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 347ms
```

**To Reproduce**
1. clone the repository
2. bump the version to 2024.1.1-beta3
3. attempt to use a gradlew task
5. See error

**Expected behavior**
It succesfully executes the task

**Environment**
OS: Linux Mint
Caching: None (manually deleted)
Commit: 4dc4d7b7798b74cf4f802668b745b856c72aaf51
Shell: Bash in TMUX

**Additional context**
![image](https://github.com/CurtinFRC/2024-Crescendo/assets/114076356/93afec45-1aca-4014-81ea-d37031b3aa8f)

**Comment by spacey-sooty** [comment]
Invalid gradle version was being used fixed now
